AWSTemplateFormatVersion: "2010-09-09"
Description: "Intentionally insecure template for testing"

Resources:
  PublicS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
