AWSTemplateFormatVersion: "2010-09-09"
Description: Intentionally insecure CloudFormation template for Checkov testing

Resources:
  PublicS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: insecure-public-bucket-example
      AccessControl: PublicReadWrite

  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${PublicS3Bucket.Arn}"
              - !Sub "${PublicS3Bucket.Arn}/*"

  InsecureIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "*"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: AdminPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
