AWSTemplateFormatVersion: "2010-09-09"
Description: "Ace IaC scanner test template"
Resources:
  BadBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      AccessControl: PublicRead
